src/components/App.tsx
src/components/model/device-footer.scss
src/components/model/device-views/collector.tsx
src/components/model/device-views/mixer/mixer.scss
src/components/model/device-views/mixer/mixer.tsx
src/components/model/device-views/shared/ball.tsx
src/components/model/device-views/shared/balls.tsx
src/components/model/device-views/spinner/spinner.tsx
src/components/model/device-views/spinner/wedge.tsx
src/components/model/device.tsx

This PR addresses the following issues:
- When mouse hover on the spinner, the percentage is not displayed
- Able to delete all the balls/wedges from the mixer/spinner tab by clicking on the minus sign. 
- When clicking on any of the buttons(+, -, ..., Mixer, Spinner, Collector and Add Device) cursor: hand symbol is not displayed
- Unable to edit the variable names for the balls in the mixer tab
- Unable to delete a specific wedge through its delete button

Address QA issues. (PT-186400407)

---

src/components/model/name-label-input.tsx

In the spinner, we were not trimming leading and trailing spaces. So if you type leading or trailing spaces for a variable label that is the same as another wedge, it doesn't match and it doesn't merge the two variables.
This trims any spaces, and matching variables now merge into a single wedge.

[186844118] Trims variable text after input before storing them

---

src/components/App.scss
src/components/App.tsx
src/components/model/model-component.scss
src/components/model/model-component.tsx

Fixes tab border width not extending to the right when there is an overflow-x and user scrolls to the right.

[186869626] Extend tab border to the right on overflow 

---

src/components/model/device-footer.tsx
src/hooks/useCodapAPI.tsx

This PR fixes the following issues caught by QA:
- If the user deletes the device and adds it again and updates the attribute name in the CODAP table, the corresponding column name in the plugin is not updated
- After deleting the attribute column in the CODAP table and when running the sampler again, the attribute column is not added again

Attribute tracking fixes (PT-186764365)

---

src/components/App.scss
src/components/model/arrow.scss
src/components/model/arrow.tsx
src/components/model/column-header.tsx
src/components/model/device-footer.scss
src/components/model/device-footer.tsx
src/components/model/device-views/collector.tsx
src/components/model/device-views/mixer.tsx
src/components/model/device-views/mixer/mixer.tsx
src/components/model/device-views/shared/ball.tsx
src/components/model/device-views/shared/balls.tsx
src/components/model/device-views/shared/mixer-frame.tsx
src/components/model/device-views/spinner/spinner.tsx
src/components/model/device-views/spinner/wedge.tsx
src/components/model/device.tsx
src/components/model/formula-editor.tsx
src/components/model/model-component.tsx
src/components/model/model-header.tsx
src/components/model/model-speed-slider.tsx
src/hooks/useAnimation.tsx
src/hooks/useCodapAPI.tsx
src/hooks/useGlobalState.tsx
src/types.tsx

This PR adds a hook and state property to manage animations during a run.
So far, the aspects of animation addressed are:
- The CODAP table opens when a run is first begun
- The speed determines the length of each step of the animation
- The speed can be adjusted during a run and this affects the look of the mixer animation
- The mixer animates during a run in the same way as the old Sampler
- After each sample is collected, results are sent to the CODAP table
- Controls are disabled while animation is running
Some remaining tasks to be done:
- If user sets speed to "fastest" during run, all remaining item need to be sent to CODAP
- Animating spinner during a run
- Animating variables moving into position below the column name
- Animating variables moving into brackets (also create the …

Sampler animates while running (PT-186764176)

---

webpack.config.js

This allows ngok (or other localhost tunnels) to serve the plugin over https.

build: Set webpack-dev-server allowedHosts to all

---

src/hooks/useCodapAPI.tsx

This fixes the issue with the rightmost child collection not being seen.  This commit also sets the title of the table.

fix: Set width of sample output table [PT-186395050]

---

src/hooks/useCodapAPI.tsx

Previously the description incorrectly used the number of samples instead of the number of variables.

fix: Experiment description items length [PT-187636376]

---

src/components/model/device-footer.tsx

This ensures the experiment number is updated when the device type is changed.
However there is a larger problem here - we are using a flag for when to create a new experiment instead of storing something like the hash of the model as a hidden column in the CODAP table and checking if the model already exists.  This needs to be fixed after discussing with Bill.

fix: Update experiment number when device type is changed [PT-187181825]

---

src/components/model/device-footer.tsx
src/components/model/formula-editor.tsx
src/hooks/useCodapAPI.tsx
src/models/device-model.tsx

The change in the work that validated the formula caused an object to be output for the formula with the value and the valid flag. This caused old files not to be loaded without a migration.  Since the valid flag can be computed there is no need to store it so the formula save state was returned to just be the value.

fix: Restore formula to just saving the value [PT-187221915]

---

src/hooks/useGlobalState.tsx

This removes the defaults dimensions in the plugin init call as they override any saved plugin size and position.

fix: Save and restore plugin size and position [PT-188326948]

---

src/components/helpers.ts
src/components/model/arrow.tsx
src/components/model/column-header.tsx
src/components/model/column.tsx
src/components/model/device-footer.tsx
src/components/model/device-views/collector.tsx
src/components/model/device-views/mixer.tsx
src/components/model/device-views/shared/ball.tsx
src/components/model/device-views/shared/balls.tsx
src/components/model/device-views/spinner/needle.tsx
src/components/model/device-views/spinner/separator-lines.tsx
src/components/model/device-views/spinner/spinner.tsx
src/components/model/device-views/spinner/text-backer.tsx
src/components/model/device-views/spinner/wedge.tsx
src/components/model/device.tsx
src/components/model/formula-editor.tsx
src/components/model/help-modal.tsx
src/components/model/model-component.tsx
src/components/model/model-header.tsx
src/components/model/name-label-input.tsx
src/components/model/percent-label-input.tsx
src/hooks/use-resizer.ts
src/hooks/useAnimation.tsx
src/hooks/useGlobalState.tsx
src/models/device-model.tsx
src/models/model-model.tsx
src/types.tsx
src/utils/id.ts

I was refactoring the code to allow for experiments without replacement and hit a type import cycle.  Instead of adding to the complexity of that PR this PR just centralizes all the types into one file to remove the import cycle.

fix: Moved all types to the types.ts file

---

src/components/model/device-footer.tsx
src/components/model/device.tsx
src/components/model/model-header.tsx
src/helpers/codap-helpers.tsx
src/helpers/model-helpers.ts
src/hooks/useAnimation.tsx
src/hooks/useGlobalState.tsx
src/types.tsx

This replaces some complex state flags with a hidden hash of the experiment contained in the data table.
This also fixes a bug where the formulas kept references to deleted device ids.  This caused experiments to hash incorrectly when devices were deleted.

feat: Use hidden experiment hash to track experiment and sample number [PT-188267656]

---

src/components/App.scss

Added overflow: auto to App class.

fix: The user can scroll the contents of the Sampler plugin [SAMPLER-18]

---

src/components/model/column-header.tsx
src/helpers/codap-helpers.tsx
src/utils/formula-parser.ts

This uses the existing formula parser to parse any formula found in the data context and a new function to rename the variable in the parsed result.

fix: Rename variables in functions when column is renamed [SAMPLER-24]

---

src/components/model/column-header.tsx
src/components/model/device.scss
src/components/model/model-component.scss

This changes the device name input to a textarea that defaults to 1 row but auto resizes to match the input.
This also fixes a bug that I noticed where users could clear the input field and set the variable name to the empty string.  Now if the user tries to do that and "blurs" the input to save it the column name is reset.

fix: Allow device name input to resize [SAMPLER-6]

---

src/components/model/device-footer.tsx

When add device is used the code used to only add one device, now it adds the same number of devices as in the column where the "Add Device" button was clicked.

fix: Add same number of devices when 'Add device' is selected [SAMPLER-8]

---

src/components/model/device-footer.tsx
src/models/device-model.tsx

Before the mixer device was always added, now the selected device type is added.

fix: Use current device type when Add Device clicked [SAMPLER-33]

---

src/components/model/device-views/spinner/spinner.tsx
src/components/model/device-views/spinner/text-over-wedge.tsx
src/components/model/device-views/spinner/wedge.tsx

This fixes multiple issues with the spinner component:
- When dragging a wedge all the wedge labels are black
- The spinner label is now displayed over the wedge and separators and is no longer clipped
- When selected the selected wedge label is black and the others are dark gray

fix: Update spinner labels [SAMPLER-29]

---

src/components/model/device.tsx

This fixes a bug where if you were editing a mixer variable and then selected the spinner the wedge for that variable was automatically selected.

fix: Clear selected variable on view change [SAMPLER-36]

---

src/utils/utils.ts

To match old Sampler plugin use "_" as the variable name when blanks are entered in the "Set Variable Names" dialog.  Previously these were skipped.
Example: the value "a, , b,    , c, d" would result in the following variables: "a, _, b, _, c, d".

fix: Use underscores for blank variables [SAMPLER-37]

---

src/components/about/about.scss
src/components/about/about.tsx

This is so when the plugin is "skinny" the text wraps around the image instead of staying in its own column.
Before:
After:

fix: Change funding image to use float [SAMPLER-38]

---

src/components/model/model-component.scss

This fix disables pointer events on the tick marks overlayed on the range input.  The tick marks were preventing the range input from getting clicks.

fix: The speed slider should respond to mouse clicks consistently [SAMPLER-40]

---

src/hooks/useAnimation.tsx
src/types.tsx

This switches from recursively calling animation() in "Fastest"" mode (which was causing a stack overflow for large number of items) to checking if the animation should instantly complete when requesting a new animation frame.

fix: Stack overflow when animating many items in "Fastest" mode [SAMPLER-42]

---

src/components/model/outputs.tsx
src/hooks/useAnimation.tsx
src/types.tsx

In select mode the number of output brackets now match the number of items.  In repeat mode an empty output bracket is maintained until the repeat condition is true.

fix: Update number of output brackets [SAMPLER-41]

---

src/hooks/useAnimation.tsx
src/utils/pattern.ts

Allows the user to enter a pattern of the outputs like "a, b" along with the existing formula input.

feat: Add until pattern support [SAMPLER-44]

---

src/components/model/device-footer.tsx
src/components/model/device.tsx

This fixes two things which were causing name changes for newly added devices to not be handled correctly.
1. It saves the CODAP id of the item when a new device is created
2. It removes the saved item attributes of any deleted columns.
With these changes notifications from CODAP on an attribute change can find the correct column to update.

fix: Attribute name change not being handled correctly [SAMPLER-32]

---

src/components/model/column-header.tsx
src/components/model/device.tsx
src/components/model/model-header.tsx
src/helpers/codap-helpers.tsx
src/hooks/useAnimation.tsx
src/utils/collector.ts
src/utils/model.ts

- When the user switches from Mixer or Spinner to the Collector, if there are no data values belonging to the output attribute, the output attribute is deleted, replaced by the set of attributes belonging to the source dataset (from which cases will be collected). If there is no source dataset, then the output attribute is not deleted because otherwise there would be no attribute at the items level.
- When the user switches from the Collector to the Mixer or Spinner, if there are no data values belonging to the source dataset attributes, these attributes are deleted. The attribute(s) associated with the Mixer or Spinner device(s) are added at the items level.
- Note that attributes that have data values are not automatically deleted during these transitions. It's up to the user to decide …

feat: Keep item attributes in sync with device changes [SAMPLER-30]

---

src/components/helpers.ts
src/components/model/device.tsx
src/types.tsx

This adds a history of wedge changes so that values are distributed over the untouched wedges.

fix: Keep history of wedge changes [SAMPLER-27]

---

src/components/App.scss
src/components/about/about.scss
src/components/measures/measures.scss
src/components/model/arrow.tsx
src/components/model/model-component.scss
src/components/model/model-component.tsx

Because the device container is absolute and can grow in width and the header is relative JavaScript must be used to keep their widths in sync.

fix: Fix model header and arrow layout when scrolling  [SAMPLER-34]

---

src/components/model/device.tsx
src/hooks/useAnimation.tsx
src/hooks/useGlobalState.tsx
src/utils/attr-map.ts
src/utils/collector.test.ts
src/utils/collector.ts

This fixes a bug encountered when the collector has a column with the same name as one of the built-in experiment columns.
This fix mimics CODAP's rename UI where it appends a number, starting at 2 until a new column is found.

fix: Rename built-in experiment columns when using collectors [SAMPLER-49]

---

src/helpers/model-helpers.ts
src/hooks/useAnimation.tsx

When the device is a Spinner, instead of reporting the number if "items" (which can often be a large number to approximate fractions), report the number if "segments" in the spinner.
When the model is hidden, the description should just be "Hidden mixer" or "Hidden spinner."
When there are multiple devices the description should just be "Multiple devices."

feat: Improvements to values for Description attribute [SAMPLER-74]

---

src/hooks/useAnimation.tsx

Previously the case selection was always skipped in fast mode.  Now the last set of generated cases is selected at the end of the experiment in fast mode.

fix: Select last generated cases at end of fast mode [SAMPLER-73]

---

src/components/common/custom-select.scss
src/components/common/custom-select.tsx

This removes the unneeded dropdown-arrow-icon.svg image tag from the custom select as it is already added in the css using an &::after rule.  Before this change there was a 404 message showing as the img src could not be resolved.  Padding has been added to take the place of the (broken) image.

fix: Remove img tag from custom select

---

src/components/model/repeat-until-modal.tsx
src/components/model/variable-setting-modal.tsx
src/hooks/use-drag-modal.ts

This moves the drag constraint code from the variable setting modal to a hook which is then used in both the variable setting and repeat until modals.
With this change touch support is also added to the repeat until modal drag handling.

fix: Added drag constraint to repeat until modal [SAMPLER-94]
