- src/components/App.tsx
- src/components/model/device.scss
- src/components/model/device.tsx
- src/components/model/model-component.tsx
- src/models/device-model.tsx
- src/models/model-model.tsx
NOTE: this does not draw the arrows between devices.
> feat: Added multi-device support [PT-186711774]

- package-lock.json
- package.json
- src/components/App.tsx
- src/components/model/device.scss
- src/components/model/device.tsx
- src/components/model/model-component.tsx
- src/models/device-model.tsx
- src/utils/id.ts
This also changes the device id from a number to a string.
> feat: Switch to useImmer for state updates

- src/components/App.tsx
- src/components/measures/measures.tsx
- src/components/model/device.scss
- src/components/model/device.tsx
- src/components/model/model-component.tsx
- src/models/device-model.tsx
- src/models/model-model.tsx
- src/utils/codap-helpers.ts
This PR does the following:
- Adds a `name` property to each device which is updated if the user changes the device name input
- Creates types for the device "inputs" or variables
- Allows user to update name of single variable (note: not dealing with multiple variables at the moment)
- Sends data to CODAP and opens table
Note, since this is only a proof of concept, this PR does **NOT** do the following, which will need to be implemented in subsequent work:
- Does not update the attribute names in the CODAP table if the device names change
- Does not update device names if the attribute names in the CODAP table change
- Does not handle multiple devices having the same name 
Question:
- Should we rename "variables" to "inputs"? It seems more descriptive to me.
> Proof of concept: model "runs" and sends data to CODAP (PT-186719024)

- src/components/App.scss
- src/components/measures/measures.scss
- src/components/model/device.scss
- src/components/model/model-component.scss
This also removes a bunch of duplicated font-size styles.
> Change to left align styling

- src/components/App.tsx
- src/components/model/device.tsx
- src/components/model/model-component.tsx
- src/models/model-model.tsx
- An "Add Branch" button button is shown instead of the "Add Device" button on the selected device after the first device is added to the right of the device
- A "Merge" button is shown in addition to the "Add Device" button for selected devices that are in a column with more than 1 device.
- Removes Collector button once there is more than 1 device
> feat: Add device branch/merge [PT-186730361]

- src/components/model/arrow.scss
- src/components/model/arrow.tsx
NOTE: this does not update the model state.  There is a TODO comment for a later PR.
> feat: Added editable arrow label [PT-186730666]

- src/components/App.tsx
- src/components/model/arrow.scss
- src/components/model/arrow.tsx
- src/components/model/column.tsx
- src/components/model/device.scss
- src/components/model/device.tsx
- src/components/model/model-component.scss
- src/components/model/model-component.tsx
Fixes column, device, and arrow styling to match spec
> 186719010 fix stylings

- src/components/App.tsx
- src/components/model/arrow.scss
- src/components/model/arrow.tsx
- src/components/model/column.tsx
- src/components/model/device-views/shared/ball.tsx
- src/components/model/device-views/shared/balls.tsx
- src/components/model/device.scss
- src/components/model/device.tsx
- src/components/model/model-component.scss
- src/components/model/model-component.tsx
Misc style fixes from these stories:
[#186730666](https://www.pivotaltracker.com/story/show/186730666) - styles arrow label input, adds tab handling.
[#186711774](https://www.pivotaltracker.com/story/show/186711774) - Eye icon is hidden when device is not selected, Model tab header expands when model content area is wider than viewable area, Device Label text box and spacing, Fixes attribute name input styling, and keyboard, and click handling(
[#186719010](https://www.pivotaltracker.com/story/show/186719010) - arrow tip more pointy
> 186711774 fix styling 2

- src/components/App.tsx
- src/components/helpers.ts
- src/components/model/column.tsx
- src/components/model/device-views/collector.tsx
- src/components/model/device-views/mixer/mixer.tsx
- src/components/model/device-views/shared/ball.tsx
- src/components/model/device-views/shared/balls.tsx
- src/components/model/device-views/spinner/spinner.tsx
- src/components/model/device-views/spinner/wedge.tsx
- src/components/model/device.tsx
- src/components/model/name-label-input.tsx
- src/components/model/percent-label-input.tsx
- src/models/device-model.tsx
- src/models/model-model.tsx
This PR makes some changes to the model so that columns have names instead of devices. This is because we want the attributes in the CODAP table to correspond to each column, not to each device.
> Send data to CODAP without delay (PT-186764245)

- src/components/App.tsx
- src/components/helpers.ts
- src/components/model/column.tsx
- src/components/model/device-views/collector.tsx
- src/components/model/device-views/mixer/mixer.tsx
- src/components/model/device-views/shared/ball.tsx
- src/components/model/device-views/shared/balls.tsx
- src/components/model/device-views/spinner/spinner.tsx
- src/components/model/device-views/spinner/wedge.tsx
- src/components/model/device.tsx
- src/components/model/name-label-input.tsx
- src/components/model/percent-label-input.tsx
- src/models/device-model.tsx
- src/models/model-model.tsx
Fixes the issue caught in this story: https://www.pivotaltracker.com/story/show/186875773
> Fix calculation of last wedge percentage. (PT-186875773)

- src/components/App.tsx
- src/components/model/column.tsx
- src/components/model/device-footer.tsx
- src/components/model/device.tsx
- src/components/model/model-component.tsx
- src/components/model/variable-setting-modal.scss
- src/components/model/variable-setting-modal.tsx
- src/utils/utils.ts
Adds functionality to the `...` (series) button.
When series button is clicked, modal to enter desired series should appear.
Enter a series in input box. If user clicks Cancel, no change is made to device. If user clicks OK or hits Enter, variable names in device changes to the series entered.
> 186844045 variable entry modal

- src/components/App.tsx
- src/components/model/arrow.scss
- src/components/model/arrow.tsx
- src/components/model/column.tsx
- src/components/model/model-component.tsx
Animates the arrow when Start button is clicked. Animation runs for the number of samples set.
The trigger to animate the arrow should be adjusted later when the devices are animated.
> 186730392 animate arrows

- src/components/model/device-footer.tsx
- src/components/model/device.tsx
- src/components/model/name-label-input.tsx
- src/models/device-model.tsx
This PR also makes an update to the types for viewType just for clarity / concision.
> User can delete all variables except last one if in the mixer (PT-186875565)

- src/components/model/arrow.tsx
- src/components/model/column.tsx
- src/components/model/device-footer.tsx
- src/components/model/device.tsx
- src/components/model/model-header.tsx
- src/hooks/useCodapAPI.tsx
- src/hooks/useGlobalState.tsx
- src/types.tsx
This PR also fixes a regression where the delete button was not showing up because I had used the wrong index check if we should show it.
> Experiment number updates when model is modified or when data is cleared. (PT-186764245)

- src/components/model/model-header.tsx
This updates the UI to fix the start/pause button label and adds a handler for the stop button.
NOTE: these handlers don't do anything yet - the animation loop will be updated in a follow on PR to allow for pausing and stopping.
> fix: Start/Pause/Stop handlers [PT-187271348]

- src/components/model/arrow.scss
- src/components/model/device-footer.tsx
- src/components/model/formula-editor.tsx
- src/hooks/useCodapAPI.tsx
- src/models/device-model.tsx
- src/utils/formula-parser.ts
- src/utils/utils.test.ts
- src/utils/utils.ts
This replaces the formula formatter that was using regexs to replace variables with a full top down parser.
This also adds UI feedback when the formula is not valid.
> feat: Replace formula formatter with full parser [PT-187221915]

- src/components/model/device-views/spinner/needle.tsx
- src/components/model/device-views/spinner/spinner.tsx
This copies over the svg needle from the original sampler and adds a sample animation while the experiment is running.  This animation will be updated when the animation loop is refactored.
> feat: Added start of animating the spinner [PT-185864784]

- src/components/measures/measures.scss
- src/components/measures/measures.tsx
- src/helpers/codap-helpers.tsx
This also updates the measures tab to clean up the UI.
> feat: Port collection measures code [PT-186400429]

- src/components/model/model-header.tsx
No PT story for this - just a UI tweak.
> fix: Change items and sample size inputs to use numbers

- src/hooks/useAnimation.tsx
- src/utils/formula-parser.ts
- src/utils/utils.ts
This was using a regex, now it extracts the variables the parser finds which is much more robust.
> fix: Change formula variable extraction to use parsed expression [PT-188328082]

- src/hooks/useAnimation.tsx
The code was using the wrong index to remove the variable for the next sample.
Also renamed the core animation setup functions to be more clear about their intent.
> fixed: Bug in without replacement code [PT-187636314]

- src/components/measures/measures.tsx
This changes the right hand side of the count and conditional count formulas in the measures tab to list the unique variables available across all the devices.
> fix: Change measures tab to use device variables [SAMPLER-17]

- src/components/model/model-component.scss
- src/components/model/model-header.tsx
- src/contants.ts
- src/helpers/codap-helpers.tsx
- src/hooks/useGlobalState.tsx
This ensures the plugin window is at least the minimum dimensions at startup.  This is a bit of a hack to get around a complex set of issues between CODAP v2 and v3 not currently having a way to tell the plugin the initial window size.
This also fixes the header styling so the horizontal scrollbar is not visible due to a padding overflow.
> fix: Ensure minimum plugin window size [SAMPLER-19]

- src/helpers/model-helpers.ts
Fixes a bug where the formula was moved to the next device when a device was deleted.
> fix: Missing formula after deleting device

- src/components/model/device-visibility.tsx
Updates the lock/unlock text to new requested values.
> fix: Update lock device text [SAMPLER-20]

- src/assets/expander.svg
- src/components/model/help-modal.tsx
- src/components/model/model-component.scss
- src/components/model/model-header.tsx
- src/helpers/codap-helpers.tsx
- src/helpers/model-helpers.ts
- src/hooks/useAnimation.tsx
- src/hooks/useGlobalState.tsx
- src/types.tsx
This updates the repeat/until UI and help UI to more closely match the spec and adds the repeat/until logic.
> feat: Add repeat/until functionality [SAMPLER-9]

- src/components/model/device-footer.tsx
This is so it fits within the column.
> fix: Update message when there is no collector available [SAMPLER-25]

- src/helpers/codap-helpers.tsx
- src/hooks/useGlobalState.tsx
- src/models/device-model.tsx
- src/types.tsx
This adds a migration step to migrate old TPSampler states to the new plugin.
> feat: Allow plugin to load TPSampler plugin state [SAMPLER-43]

- src/components/App.scss
This also fixes the arrow layout issue.
This may not be the final resolution if they want the scrollbars back though.
> fix: Remove scrollbars to fix header width issue [SAMPLER-34]

- src/components/helpers.ts
- src/components/model/device-footer.tsx
- src/components/model/device.tsx
- src/components/model/percent-label-input.tsx
This handles cases when the user enters 0, 100, negative numbers and a percentages that add up greater to 100.
> fix: Add special case handling for percentages [SAMPLER-27]

- src/assets/with-replacement-icon.svg
- src/assets/without-replacement-icon.svg
- src/components/common/custom-select.scss
- src/components/common/custom-select.tsx
- src/components/model/device-footer.tsx
- src/components/model/device-replacement.scss
- src/components/model/device-replacement.tsx
- src/components/model/device-visibility.scss
- src/components/model/device-visibility.tsx
- src/components/model/device.tsx
- src/components/model/model-component.scss
- src/components/model/model-header.tsx
- src/helpers/model-helpers.ts
- src/hooks/useAnimation.tsx
- src/hooks/useGlobalState.tsx
- src/models/device-model.tsx
- src/types.tsx
This moves the replacement setting from the model level down to the per device level.
> feat: Move replacement setting to device level [SAMPLER-83]

- src/hooks/useAnimation.tsx
- src/utils/unique-values.ts
This adds the evaluation of the number of unique values repeat until condition.
> feat: Add unique value count evaluation [SAMPLER-80]
